In [1]:
import pandas as pd
import numpy as np
import os
data = pd.read_csv("Housing.csv")

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [3]:
data.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [4]:
data.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [5]:
data['guestroom'].unique()

array(['no', 'yes'], dtype=object)

In [6]:
data['code']=pd.factorize(data.guestroom)[0]
data.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  code  
0              no             yes        2      yes        furnished     0  
1              no             yes        3       no        furnished     0  
2              no              no        2      yes   semi-furnished     0  
3              no             yes        3      yes        furnished     0  
4              no             yes        2       no        furnished     1

In [71]:
data['guestroom'].value_counts()

guestroom
no     448
yes     97
Name: count, dtype: int64

In [72]:
data['code'].value_counts()

code
0    448
1     97
Name: count, dtype: int64

In [73]:
columns=['bathrooms','bedrooms','code']
X = data[columns]
X

bathrooms  bedrooms  code
0            2         4     0
1            4         4     0
2            2         3     0
3            2         4     0
4            1         4     1
..         ...       ...   ...
540          1         2     0
541          1         3     0
542          1         2     0
543          1         3     0
544          1         3     0

[545 rows x 3 columns]

In [74]:
y = data['price']
y

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...   
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [75]:
from sklearn.model_selection import train_test_split
X_test, X_train, y_test, y_train = train_test_split(X, y, test_size = 0.4, random_state = 30)

In [76]:
X_train

bathrooms  bedrooms  code
351          1         2     0
235          1         3     1
60           2         3     1
126          1         3     0
357          1         4     0
..         ...       ...   ...
254          1         4     0
2            2         3     0
296          2         3     0
418          1         4     0
542          1         2     0

[218 rows x 3 columns]

In [77]:
y_train

351     3780000
235     4620000
60      7140000
126     5880000
357     3773000
         ...   
254     4480000
2      12250000
296     4200000
418     3360000
542     1750000
Name: price, Length: 218, dtype: int64

In [78]:
from sklearn.linear_model import LinearRegression

In [79]:

rs = LinearRegression()
rs

LinearRegression()

In [80]:
# taining the model
rs.fit(X_train,y_train)

LinearRegression()

In [81]:
#y intercept (y = mx +c)
c = rs.intercept_
c

1728586.331409623

In [82]:
# coefficient

m= rs.coef_
m

array([1206948.63844849,  473256.29372548,  658870.81837075])

In [83]:
y_predict_train =rs.predict(X_train)
y_predict_test =rs.predict(X_test)

In [84]:
y_predict_train

array([3882047.55730906, 5014174.66940529, 6221123.30785378,
       4355303.85103454, 4828560.14476002, 4355303.85103454,
       4355303.85103454, 4355303.85103454, 4355303.85103454,
       4540918.37567981, 5487430.96313077, 4355303.85103454,
       6221123.30785378, 3882047.55730906, 3882047.55730906,
       6221123.30785378, 4355303.85103454, 6035508.78320851,
       3882047.55730906, 3882047.55730906, 3882047.55730906,
       3882047.55730906, 5014174.66940529, 4540918.37567981,
       6221123.30785378, 5014174.66940529, 5562252.48948303,
       3882047.55730906, 5562252.48948303, 5562252.48948303,
       5562252.48948303, 4355303.85103454, 6035508.78320851,
       4828560.14476002, 5562252.48948303, 3882047.55730906,
       4355303.85103454, 5014174.66940529, 3882047.55730906,
       4540918.37567981, 5014174.66940529, 4355303.85103454,
       4355303.85103454, 4355303.85103454, 3882047.55730906,
       6035508.78320851, 6694379.60157925, 4355303.85103454,
       3882047.55730906,

In [85]:
y_predict_test

array([6221123.30785378, 3882047.55730906, 4355303.85103454,
       7242457.42165699, 5088996.19575755, 5562252.48948303,
       4355303.85103454, 5562252.48948303, 3882047.55730906,
       4355303.85103454, 5014174.66940529, 3882047.55730906,
       6694379.60157925, 4355303.85103454, 3882047.55730906,
       4355303.85103454, 5960687.25685624, 4355303.85103454,
       3882047.55730906, 4355303.85103454, 4355303.85103454,
       3882047.55730906, 4355303.85103454, 5747867.0141283 ,
       4828560.14476002, 5487430.96313077, 6035508.78320851,
       3882047.55730906, 4355303.85103454, 4828560.14476002,
       5014174.66940529, 5562252.48948303, 3882047.55730906,
       4355303.85103454, 5562252.48948303, 4355303.85103454,
       5562252.48948303, 5014174.66940529, 4355303.85103454,
       4355303.85103454, 4355303.85103454, 4355303.85103454,
       4355303.85103454, 4355303.85103454, 3882047.55730906,
       5562252.48948303, 4355303.85103454, 4828560.14476002,
       4355303.85103454,

In [86]:
from sklearn.metrics import r2_score
r2_score(y_test,y_predict_test)

0.4046766480945394